#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BuildUp_teretana;

namespace BuildUp_teretana	
{
	public partial class Clan
	{
		private int _brojIskaznice;
		public virtual int BrojIskaznice
		{
			get
			{
				return this._brojIskaznice;
			}
			set
			{
				this._brojIskaznice = value;
			}
		}
		
		private string _ime;
		public virtual string Ime
		{
			get
			{
				return this._ime;
			}
			set
			{
				this._ime = value;
			}
		}
		
		private string _prezime;
		public virtual string Prezime
		{
			get
			{
				return this._prezime;
			}
			set
			{
				this._prezime = value;
			}
		}
		
		private string _adresa;
		public virtual string Adresa
		{
			get
			{
				return this._adresa;
			}
			set
			{
				this._adresa = value;
			}
		}
		
		private string _kontakt;
		public virtual string Kontakt
		{
			get
			{
				return this._kontakt;
			}
			set
			{
				this._kontakt = value;
			}
		}
		
		private System.Nullable<System.Char> _spol;
		public virtual System.Nullable<System.Char> Spol
		{
			get
			{
				return this._spol;
			}
			set
			{
				this._spol = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private IList<VrijemeNaSpravi> _vrijemeNaSpravis = new List<VrijemeNaSpravi>();
		public virtual IList<VrijemeNaSpravi> VrijemeNaSpravis
		{
			get
			{
				return this._vrijemeNaSpravis;
			}
		}
		
		private IList<Izvjesce> _izvjesces = new List<Izvjesce>();
		public virtual IList<Izvjesce> Izvjesces
		{
			get
			{
				return this._izvjesces;
			}
		}
		
		private IList<Clanarina> _clanarinas = new List<Clanarina>();
		public virtual IList<Clanarina> Clanarinas
		{
			get
			{
				return this._clanarinas;
			}
		}
		
	}
}
#pragma warning restore 1591
