#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace BuildUp_teretana	
{
	public partial class Obavljeni_izvještaji
	{
		private int _iD_obavljeni;
		public virtual int ID_obavljeni
		{
			get
			{
				return this._iD_obavljeni;
			}
			set
			{
				this._iD_obavljeni = value;
			}
		}
		
		private string _mjesec;
		public virtual string Mjesec
		{
			get
			{
				return this._mjesec;
			}
			set
			{
				this._mjesec = value;
			}
		}
		
		private string _godina;
		public virtual string Godina
		{
			get
			{
				return this._godina;
			}
			set
			{
				this._godina = value;
			}
		}
		
		private bool? _poslano;
		public virtual bool? Poslano
		{
			get
			{
				return this._poslano;
			}
			set
			{
				this._poslano = value;
			}
		}
		
	}
}
#pragma warning restore 1591
