#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BuildUp_teretana;

namespace BuildUp_teretana	
{
	public partial class Sprava
	{
		private int _iD_sprave;
		public virtual int ID_sprave
		{
			get
			{
				return this._iD_sprave;
			}
			set
			{
				this._iD_sprave = value;
			}
		}
		
		private string _naziv;
		public virtual string Naziv
		{
			get
			{
				return this._naziv;
			}
			set
			{
				this._naziv = value;
			}
		}
		
		private int? _prosjecna_potrosnja_kalorija;
		public virtual int? Prosjecna_potrosnja_kalorija
		{
			get
			{
				return this._prosjecna_potrosnja_kalorija;
			}
			set
			{
				this._prosjecna_potrosnja_kalorija = value;
			}
		}
		
		private IList<VrijemeNaSpravi> _vrijemeNaSpravis = new List<VrijemeNaSpravi>();
		public virtual IList<VrijemeNaSpravi> VrijemeNaSpravis
		{
			get
			{
				return this._vrijemeNaSpravis;
			}
		}
		
	}
}
#pragma warning restore 1591
