#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using BuildUp_teretana;

namespace BuildUp_teretana	
{
	public partial class VrijemeNaSpravi
	{
		private int _brojIskaznice;
		public virtual int BrojIskaznice
		{
			get
			{
				return this._brojIskaznice;
			}
			set
			{
				this._brojIskaznice = value;
			}
		}
		
		private int _iD_sprave;
		public virtual int ID_sprave
		{
			get
			{
				return this._iD_sprave;
			}
			set
			{
				this._iD_sprave = value;
			}
		}
		
		private int? _vrijeme;
		public virtual int? Vrijeme
		{
			get
			{
				return this._vrijeme;
			}
			set
			{
				this._vrijeme = value;
			}
		}
		
		private Clan _clan;
		public virtual Clan Clan
		{
			get
			{
				return this._clan;
			}
			set
			{
				this._clan = value;
			}
		}
		
		private Sprava _sprava;
		public virtual Sprava Sprava
		{
			get
			{
				return this._sprava;
			}
			set
			{
				this._sprava = value;
			}
		}
		
	}
}
#pragma warning restore 1591
